

# Display example
# FROM node:latest
# RUN npm install -g serve
# COPY ./display ./display
# CMD serve ./display #shell format, not preferred


# From Plug-in Extension
# FROM node:8.9-alpine
# ENV NODE_ENV production
# WORKDIR /usr/src/app
# COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
# RUN npm install --production --silent && mv node_modules ../
# COPY . .
# EXPOSE 3000
# CMD npm start